In [ ]:
!nvidia-smi

Tue Aug 17 00:20:57 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P0    29W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
pip list | grep torch

torch                         1.9.0+cu102
torchsummary                  1.5.1
torchtext                     0.10.0
torchvision                   0.10.0+cu102


In [ ]:
import torch
import numpy as np

In [42]:
## 여러가지 기본 함수들

In [ ]:
# torch의 arange
nums = torch.arange(9)

# torch의 shape
nums.shape

# torch의 numpy array
nums.numpy()

# torch의 reshape (.view()와 비슷)
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
## 랜덤 행렬

In [ ]:
randoms = torch.rand((3,3))
randoms

tensor([[0.6156, 0.3291, 0.3990],
        [0.6177, 0.1712, 0.1399],
        [0.7183, 0.7155, 0.3143]])

In [ ]:
## 영행렬, 1인 행렬 만들기

In [ ]:
zeros = torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
ones = torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
zeros.shape

torch.Size([3, 3])

In [27]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [28]:
nums = nums.reshape((3,3))

In [29]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
## 연산 하기

In [30]:
result = torch.add(nums, 10)
result

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [ ]:
## 쉐입 바꾸기

In [34]:
range_nums = torch.arange(9).reshape((3,3))
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [32]:
result.numpy()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [35]:
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
range_nums.view(1,9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
## 슬라이싱

In [38]:
nums[1]

tensor([3, 4, 5])

In [39]:
nums[1,1]

tensor(4)

In [40]:
nums[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

In [41]:
nums[1:, 1:]

tensor([[4, 5],
        [7, 8]])

In [ ]:
## torch로 tensor 만들기

In [43]:
arr = np.array([1, 1, 1])
arr

array([1, 1, 1])

In [44]:
arr_torch = torch.from_numpy(arr)
arr_torch

tensor([1, 1, 1])

In [ ]:
## 형태 변환

In [45]:
arr_torch.float()

tensor([1., 1., 1.])

In [46]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [47]:
# gpu 연산할 때 gpu로 보내는 방법
arr_torch.to(device)

tensor([1, 1, 1], device='cuda:0')

In [48]:
# 연산하고 다시 cpu로
arr_torch.to('cpu')

tensor([1, 1, 1])

In [57]:
# required_grad = True -> grad 계산할 때 업데이트를 하겠다는 것
x = torch.ones(2,2, requires_grad=True)

In [58]:
y = x+2

In [59]:
z = y*y*3
out = z.mean()

In [60]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [61]:
# out에 대한 x의 grad 구하기
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [65]:
x.requires_grad

True

In [67]:
y.requires_grad

True

In [68]:
with torch.no_grad():
    print((x**2).requires_grad)

False


In [69]:
from torchvision import datasets, transforms

In [71]:
batch_size = 32
test_batch_size = 32

In [75]:
train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('dataset/', train=True, download=True,
                   transform = transforms.Compose([
                        transforms.ToTensor(),
                        transforms.Normalize(mean=(0.5, ), std=(0.5, ))
                   ])),
                   batch_size=batch_size,
                   shuffle=True

)

Failed to download (trying next):
HTTP Error 503: Service Unavailable



  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting dataset/MNIST/raw/train-images-idx3-ubyte.gz to dataset/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting dataset/MNIST/raw/train-labels-idx1-ubyte.gz to dataset/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting dataset/MNIST/raw/t10k-images-idx3-ubyte.gz to dataset/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting dataset/MNIST/raw/t10k-labels-idx1-ubyte.gz to dataset/MNIST/raw



/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
