In [7]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [8]:
tf.random.set_seed(42)

In [9]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [10]:
x_data = np.array([[h]], dtype=np.float32)
x_data

array([[[1., 0., 0., 0.]]], dtype=float32)

In [11]:
# sample 수(배치), token 수, token의 임베딩
x_data.shape

(1, 1, 4)

In [12]:
hidden_size = 2

# 마지막 레이어의 units가 2니까 output은 2
cell = layers.SimpleRNNCell(units = hidden_size)

# return_sequences: bool 형태로 T면 output 전체를 출력하는 것이고, F면 마지막 output만 출력
# return_state: bool 형태로 output에 더해 마지막 상태도 반환할지 결정하는 것
rnn = layers.RNN(cell, return_sequences = True, return_state = True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states: {} \t shape: {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4)
output : [[[ 0.31773362 -0.11744198]]] 	 shape : (1, 1, 2)
states: [[ 0.31773362 -0.11744198]] 	 shape: (1, 2)


2021-07-29 09:58:29.049470: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [14]:
# cell 과 rnn 합치기

rnn = layers.SimpleRNN(units=hidden_size, return_sequences = True, return_state = True)

output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states: {} \t shape: {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4)
output : [[[ 0.54152584 -0.00444528]]] 	 shape : (1, 1, 2)
states: [[ 0.54152584 -0.00444528]] 	 shape: (1, 2)


In [19]:
### 여러개 넣어보기
### shape를 이해하자!

In [15]:
x_data = np.array([[h,e,l,l,o]], dtype=np.float32)

In [16]:
x_data.shape

(1, 5, 4)

In [17]:
# cell 과 rnn 합치기

rnn = layers.SimpleRNN(units=hidden_size, return_sequences = True, return_state = True)

output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states: {} \t shape: {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]] 	 shape : (1, 5, 4)
output : [[[-0.12818007  0.04968958]
  [-0.12667213 -0.66418386]
  [ 0.13962443  0.6124754 ]
  [-0.57845664 -0.30636993]
  [ 0.4918073   0.28548098]]] 	 shape : (1, 5, 2)
states: [[0.4918073  0.28548098]] 	 shape: (1, 2)


In [20]:
### batch 사이즈 바꿔보기

x_data = np.array([[h, e, l, l, o], [e, o, l, l, l], [l, l, e, e, l]], dtype=np.float32)

In [22]:
rnn = layers.SimpleRNN(units=hidden_size, return_sequences = True, return_state = True)

output, states = rnn(x_data)

print('x_data : {} \t shape : {}'.format(x_data, x_data.shape))
print('output : {} \t shape : {}'.format(output, output.shape))
print('states: {} \t shape: {}'.format(states, states.shape))

x_data : [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]] 	 shape : (3, 5, 4)
output : [[[-0.5304687   0.57137597]
  [ 0.87748414  0.40262657]
  [-0.15409182  0.9395285 ]
  [ 0.764736    0.9411049 ]
  [-0.5227913   0.7928031 ]]

 [[ 0.5604558   0.15501074]
  [-0.63670427  0.2777531 ]
  [ 0.81426847  0.73489136]
  [ 0.0509788   0.9641684 ]
  [ 0.68349284  0.95287776]]

 [[ 0.41863734  0.7525188 ]
  [ 0.3901993   0.9507177 ]
  [ 0.6133735   0.8276926 ]
  [ 0.42978778  0.8248128 ]
  [ 0.40924856  0.9569795 ]]] 	 shape : (3, 5, 2)
states: [[-0.5227913   0.7928031 ]
 [ 0.68349284  0.95287776]
 [ 0.40924856  0.9569795 ]] 	 shape: (3, 2)


In [24]:
# 한글도 해보자

idx2char = ['토', '마', '를', '먹', '자']
x_data = [[0, 0, 1, 2, 4, 3]] # 토 토 마 를 자 먹
y_data = [[0, 1, 0, 2, 3, 4]] # 토 마 토 를 먹 자

input_dim = 5
sequence_len = 6
learning_rate = 0.1

# onehot
x_one_hot = tf.keras.utils.to_categorical(x_data, num_classes=input_dim)
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=input_dim)

In [30]:
from tensorflow.keras.models import Model

model = tf.keras.Sequential()
cell = layers.SimpleRNNCell(units=input_dim, input_shape=(sequence_len, input_dim))

model.add(layers.RNN(cell=cell, return_sequences=True, return_state=False, input_shape=(sequence_len, input_dim)))
=
# 모든 타임 스텝에서 출력을 Dense 층에 적용하는 역할을 한다. 쉽게 말해 매 스텝마다 FC가 연결된 것처럼 이해할 수 있다. 각 타임 스텝을 별개의 샘플처럼 다루도록 입력의 크기를 바꾸어 이를 효과적으로 수행한다. 
model.add(layers.TimeDistributed(layers.Dense(units = input_dim, activation='softmax')))

model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate), metrics=['acc'])

In [33]:
model.summary()
model.fit(x_one_hot, y_one_hot, epochs=10)

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
rnn_3 (RNN)                  (None, 6, 5)              55        
_________________________________________________________________
time_distributed_1 (TimeDist (None, 6, 5)              30        
Total params: 85
Trainable params: 85
Non-trainable params: 0
_________________________________________________________________
Epoch 1/10
1/1 [==============================] - 0s 2ms/step - loss: 1.2780 - acc: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 3ms/step - loss: 1.0415 - acc: 1.0000
Epoch 3/10
1/1 [==============================] - 0s 2ms/step - loss: 0.8512 - acc: 0.8333
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 0.6905 - acc: 0.8333
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 0.5457 - acc: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - l

In [39]:
for i, word in enumerate(pred):
    print([idx2char[c] for c in np.argmax(word, axis=1)])

['토', '마', '토', '를', '먹', '자']


## imdb

In [41]:
import tensorflow as tf
import tensorflow_datasets as tfds

imdb, info = tfds.load("imdb_reviews", with_info=True, as_supervised=True)

In [42]:
import numpy as np

train_data, test_data = imdb['train'], imdb['test']
training_sentences = []
training_labels = []

testing_sentences = []
testing_labels= []

# numpy array로 바꾼 후 utf-8로 디코딩
for s, l in train_data:
    training_sentences.append(s.numpy().decode('utf8'))
    training_labels.append(l.numpy())

for s, l in test_data:
    testing_sentences.append(s.numpy().decode('utf8'))
    testing_labels.append(l.numpy())

In [43]:
training_labels = np.array(training_labels)
testing_labels = np.array(testing_labels)

In [58]:
vocab_size = 10000
embedding_dim = 200
max_length = 120
trunc_type = 'post'
oov_tok = '<oov>'

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words = vocab_size, oov_token = oov_tok)
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(training_sentences)
padded = pad_sequences(sequences, maxlen = max_length, truncating = trunc_type)

# testing은 알지 못하는 자료이니 fit_on_text 하면 안 됨!
testing_sequence = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sequence, maxlen = max_length, truncating = trunc_type)

In [59]:
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

def decode_review(text):
    return ' '.join([reverse_word_index.get(i, '?') for i in text])

decode_review(padded[3])

'? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? this is the kind of film for a snowy sunday afternoon when the rest of the world can go ahead with its own business as you <oov> into a big arm chair and <oov> for a couple of hours wonderful performances from cher and nicolas cage as always gently row the plot along there are no <oov> to cross no dangerous waters just a warm and witty <oov> through new york life at its best a family film in every sense and one that deserves the praise it received'

In [93]:
model = tf.keras.Sequential([tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
                             tf.keras.layers.SimpleRNN(units=50, input_shape=(max_length, embedding_dim)),
                             tf.keras.layers.Dense(128, activation='relu'),
                            tf.keras.layers.Dense(1, activation='sigmoid')])
model.summary()

Model: "sequential_21"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_15 (Embedding)     (None, 120, 200)          2000000   
_________________________________________________________________
simple_rnn_22 (SimpleRNN)    (None, 50)                12550     
_________________________________________________________________
dense_36 (Dense)             (None, 128)               6528      
_________________________________________________________________
dense_37 (Dense)             (None, 1)                 129       
Total params: 2,019,207
Trainable params: 2,019,207
Non-trainable params: 0
_________________________________________________________________


In [94]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics = ['acc'])

In [95]:
NUM_EPOCHS = 20

history = model.fit(padded, training_labels, validation_data=(testing_padded, testing_labels),
                    epochs=NUM_EPOCHS, batch_size=100)

Epoch 1/20
250/250 [==============================] - 13s 49ms/step - loss: 0.6898 - acc: 0.5336 - val_loss: 0.6815 - val_acc: 0.5667
Epoch 2/20
250/250 [==============================] - 11s 43ms/step - loss: 0.6407 - acc: 0.6264 - val_loss: 0.5390 - val_acc: 0.7444
Epoch 3/20
250/250 [==============================] - 10s 42ms/step - loss: 0.4555 - acc: 0.7864 - val_loss: 0.5790 - val_acc: 0.7407
Epoch 4/20
250/250 [==============================] - 10s 42ms/step - loss: 0.1940 - acc: 0.9258 - val_loss: 0.8281 - val_acc: 0.6637
Epoch 5/20
250/250 [==============================] - 10s 40ms/step - loss: 0.0481 - acc: 0.9850 - val_loss: 1.1393 - val_acc: 0.6845
Epoch 6/20
250/250 [==============================] - 10s 40ms/step - loss: 0.0116 - acc: 0.9969 - val_loss: 1.3423 - val_acc: 0.7141
Epoch 7/20
250/250 [==============================] - 10s 40ms/step - loss: 0.0075 - acc: 0.9978 - val_loss: 1.5510 - val_acc: 0.7012
Epoch 8/20
250/250 [==============================] - 10s 39ms