## 결측치 처리

- 소량일 때는 대표되는 값(평균 같은)으로 넣을 수 있음
- Null이 너무 많을 때는 drop하기도 함 (데이터 문제일 수도 있으니 재수집하는 것도 방법)
- 애매한 분량일 때는? 데이터 구조도를 다시 확인하고, 어떻게 처리할지 확인할 필요가 있음

## LabelEncoder (문자열 카테고리를 숫자형 카테고리로 변환)

- 레이블 인코딩이 숫자의 크고 작음이 있는 값으로 변환되면서 특정 ML 알고리즘에서 가중치가 더 부여되는 문제가 발생  
  (레이블은 0 이상의 숫자들을 일렬로 나열하는데, ML 연산 과정에서 숫자가 큰 것이 더 중요하다고 생각할 수 있음)
- 트리 계열의 알고리즘은 문제가 없으나 선형회귀 알고리즘은 문제 발생
- 원-핫 인코딩이 이 문제들을 해결

In [13]:
from sklearn.preprocessing import LabelEncoder

items = ["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print("인코딩 변환값: ", labels)
print("인코딩 클래스: ", encoder.classes_)
print("디코딩 원본값: ", encoder, encoder.inverse_transform([4,4,2]))

인코딩 변환값:  [0 1 4 5 3 3 2 2]
인코딩 클래스:  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값:  LabelEncoder() ['전자레인지' '전자레인지' '믹서']


## OneHotEncoder

- 데이터들을 벡터공간에 늘어 놓고, 해당되는 부분은 1 나머지는 0 값을 지는 벡터로 변환하는 것
- sklearn에서는 labelencoder 먼저 하고 onehotencoder를 적용해야함

In [26]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환 : 행의 -1은 '뒤에 지정한 열기준으로 원래 데이터를 나눠서 알아서 행을 채워줘라'라는 의미
labels = labels.reshape(-1, 1)

# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print("원-핫 인코딩 데이터")
print(oh_labels.toarray())
print("원-핫 인코딩 데이터 차원")
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


### 판다스 활용해서 One-Hot vector 더 빠르게 만들 수 있음!

- sklearn에서 처럼 문자열을 숫자형으로 바꾼 후 one-hot할 필요가 없음
- 바로 적용가능함.

In [29]:
import pandas as pd

df = pd.DataFrame({"item":["TV", "냉장고", "전자레인지", "컴퓨터", "선풍기", "선풍기", "믹서", "믹서"]})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

## Feature scaling

- 두 변수 중 하나의 값이 너무 클 경우 학습을 시킬 때, 가중치가 불균형하게 반영될 수 있음.
- 학습 시 속도 및 정확도를 고려해서 값을 축소하여 균형을 맞춰주는 것 (표준화 & 정규화)

##### - 표준화 (StandardScaler): 데이터의 피처 각각이 평균 0, 분산이 1인 가우시안 정규 분포를 가진 값으로 변환하는 것
##### - 정규화 (MinMaxScaler): 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해 주는 개념

## StandardScaler

In [32]:
from sklearn.datasets import load_iris
import pandas as pd

# 붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print("feature들의 평균 값")
print(iris_df.mean())
print("\nfeature들의 분산 값")
print(iris_df.var())

feature들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


### 데이터들을 표준화 하자! -> 이상치 제거

In [34]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# StandardScaler로 데이터 셋 변환. fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 scale 변환된 데이터 셋이 numpy ndarray로 반환되어 이를 DataFrame으로 만들기
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print("feature들의 평균 값")
print(iris_df_scaled.mean())
print("\nfeature들의 분산 값")
print(iris_df_scaled.var())

feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### 데이터들을 정규화 하자! -> 데이터 간 차이를 줄이자

In [35]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# MinMaxScaler로 데이터 셋 변환. fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 scale 변환된 데이터 셋이 numpy ndarray로 반환되어 이를 DataFrame으로 만들기
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print("feature들의 평균 값")
print(iris_df_scaled.mean())
print("\nfeature들의 분산 값")
print(iris_df_scaled.var())

feature들의 평균 값
sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64

feature들의 분산 값
sepal length (cm)    0.052908
sepal width (cm)     0.032983
petal length (cm)    0.089522
petal width (cm)     0.100869
dtype: float64


### feature scaling 시 주의할 점

In [41]:
# 학습 데이터는 0부터 10까지, 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler 클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1, 1)로 차원 변경
train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

# 최소값 0, 최대값 1로 변환하는 MinMaxSclaer 객체 생성
scaler = MinMaxScaler()

# fit()하게 되면 train_array 데이터의 최소값이 0, 최대값이 10으로 설정.
scaler.fit(train_array)
# 1/10 scale로 train_array 데이터 변환함. 원본 10 -> 1로 변환됨.
train_scaled = scaler.transform(train_array)

# test_array에 Scale 변환을 할 때는 반드시!! fit()을 호출하지 않고 transform() 만으로 변환해야 함.
test_scaled = scaler.transform(test_array)

In [43]:
# 앞에서 생성한 MinMaxScaler에 test_array를 fit()하게 되면 test array의 최소값 최대값이 다시 적용됨
scaler.fit(test_array)

# 1/5 scale로 test_array 데이터 변환함. 원본 5 -> 1로 변환
test_scaled = scaler.transform(test_array)

print("원본 test_array 데이터: ", np.round(test_array.reshape(-1),2))
print("Scale된 test_array 데이터: ", np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터:  [0 1 2 3 4 5]
Scale된 test_array 데이터:  [0.  0.2 0.4 0.6 0.8 1. ]


##### 학습 데이터와 테스트 데이터의 스케일링할 때, 둘이 같은 조건으로 전처리가 되도록 하는 것이 중요! 
##### 데이터 분리하기 전에 먼저 전처리하고 split하는 것이 중요!
##### 위의 내용이 여의치 않다면 테스트 데이터 변환 시에는 fit()이나, fit_transform()을 적용하지 않고 학습데이터로 이미 fit된 scaler 객체를 이용해 transfrom()으로 변환